document.write(" <div id=\"northampton_dialog\"  style=\"display:none\" title=\"University of Northampton Information\">");
document.write("        <div class=\"Content\">");
document.write("            <nav>");
document.write("                <ul>");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-graduation-cap\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#courses\" onclick=\"javascript:showInfo('azindex');\"><span>Courses<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-envelope-o\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#contacts\" onclick=\"javascript:showInfo('contact_index');\"><span>Contact Information<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-university\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#\" onclick=\"javascript:showInfo('scholarships');\"><span>Scholarships<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-comment\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#\" onclick=\"javascript: showInfo('testimonials');\" ><span>Testimonials<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-picture-o\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#gallery\" onclick=\"javascript:showInfo('gallery');\"><span>Gallery<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-at\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#social_media\" onclick=\"javascript:showInfo('social_media');\"><span>Social Media Links<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("                <\/ul>");
document.write("            <\/nav>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"azindex\" class=\"menus\" style=\"display:none\">");
document.write("            <ul id=\"index\">");
document.write("                <li><a href=\"#a2\" onclick=\"showCourses('a2');\">A<\/a><\/li>");
document.write("                <li><a href=\"#b2\" onclick=\"showCourses('b2');\">B<\/a><\/li>");
document.write("                <li><a href=\"#c2\" onclick=\"showCourses('c2');\">C<\/a><\/li>");
document.write("                <li><a href=\"#d2\" onclick=\"showCourses('d2');\">D<\/a><\/li>");
document.write("                <li><a href=\"#e2\" onclick=\"showCourses('e2');\">E<\/a><\/li>");
document.write("                <li><a href=\"#f2\" onclick=\"showCourses('f2');\">F<\/a><\/li>");
document.write("                <li><a href=\"#g2\" onclick=\"showCourses('g2');\">G<\/a><\/li>");
document.write("                <li><a href=\"#h2\" onclick=\"showCourses('h2');\">H<\/a><\/li>");
document.write("                <li><a href=\"#i2\" onclick=\"showCourses('i2');\">I<\/a><\/li>");
document.write("                <li><a href=\"#j2\" onclick=\"showCourses('j2');\">J<\/a><\/li>");
document.write("                <li><a href=\"#k2\" onclick=\"showCourses('k2');\">K<\/a><\/li>");
document.write("                <li><a href=\"#l2\" onclick=\"showCourses('l2');\">L<\/a><\/li>");
document.write("                <li><a href=\"#m2\" onclick=\"showCourses('m2');\">M<\/a><\/li>");
document.write("                <li><a href=\"#n2\" onclick=\"showCourses('n2');\">N<\/a><\/li>");
document.write("                <li><a href=\"#o2\" onclick=\"showCourses('o2');\">O<\/a><\/li>");
document.write("                <li><a href=\"#p2\" onclick=\"showCourses('p2');\">P<\/a><\/li>");
document.write("                <li><a href=\"#q2\" onclick=\"showCourses('q2');\">Q<\/a><\/li>");
document.write("                <li><a href=\"#r2\" onclick=\"showCourses('r2');\">R<\/a><\/li>");
document.write("                <li><a href=\"#s2\" onclick=\"showCourses('s2');\">S<\/a><\/li>");
document.write("                <li><a href=\"#t2\" onclick=\"showCourses('t2');\">T<\/a><\/li>");
document.write("                <li><a href=\"#u2\" onclick=\"showCourses('u2');\">U<\/a><\/li>");
document.write("                <li><a href=\"#v2\" onclick=\"showCourses('v2');\">V<\/a><\/li>");
document.write("                <li><a href=\"#w2\" onclick=\"showCourses('w2');\">W<\/a><\/li>");
document.write("                <li><a href=\"#x2\" onclick=\"showCourses('x2');\">X<\/a><\/li>");
document.write("                <li><a href=\"#y2\" onclick=\"showCourses('y2');\">Y<\/a><\/li>");
document.write("                <li><a href=\"#z2\" onclick=\"showCourses('z2');\">Z<\/a><\/li>");
document.write("            <\/ul>");
document.write("");
document.write("            <div id=\"course_content\" style=\"text-align:left;\">");
document.write("                <div id=\"a2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>A<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"b2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>B<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"c2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>C<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"d2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>D<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"e2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>E<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"f2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>F<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"g2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>G<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"h2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>H<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"i2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>I<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"j2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>J<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"k2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>K<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"l2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>L<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"m2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>M<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"n2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>N<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"o2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>O<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"p2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>P<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"q2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>Q<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"r2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>R<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"s2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>S<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"t2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>T<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"u2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>U<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"v2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>V<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"w2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>W<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"x2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>X<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"y2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>Y<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"z2\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>Z<\/h2>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("");
document.write("        <\/div><!--End of div for the a-z index-->");
document.write("");
document.write("        <div id=\"contact_index\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"contact_details\" style=\"text-align:center; margin-top: 16px;\">");
document.write("                <h3 style=\"color:#ffff80; text-decoration: underline;\">University of Northampton - Main Contact Details<\/h3>");
document.write("");
document.write("                The University of Northampton<br \/>");
document.write("                Park Campus<br \/>");
document.write("                Boughton Green Road<br \/>");
document.write("                Northampton<br \/>");
document.write("                NN2 7AL<br \/>");
document.write("                <br \/> ");
document.write("                The University of Northampton<br \/>");
document.write("                Avenue Campus<br \/>");
document.write("                St George’s Avenue<br \/>");
document.write("                Northampton<br \/>");
document.write("                NN2 6JD<br \/>");
document.write("                <br \/>");
document.write("                <strong>Tel:<\/strong> 01604 735500 (switchboard)<br \/>");
document.write("                <strong>Fax:<\/strong> 01604 720636<br \/><br \/>");
document.write("");
document.write("                <strong>Study Enquiries<\/strong><br \/>");
document.write("                <strong>Tel:<\/strong> 0300 303 2772 (Course freephone)<br \/>");
document.write("                <strong>Email:<\/strong>study@northampton.ac.uk<br \/>");
document.write("");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"scholarships\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"scholarship_details\" style=\"text-align:center; margin-top: 16px;\">");
document.write("               <h3 style=\"color:#fff; background-color: #e6005c; padding: 10px 0 10px 0;\">University Scholarships<\/h3>");
document.write("                    <h4 style=\"color:#000; background-color: #bfbfbf;\">High Achievers Scholarship<\/h4>");
document.write("                        <p>This scholarship is open to applicants who are predicted, and achieve, ABB+ grades or higher from 3 A levels.<br \/>");
document.write("                        There will be a maximum of 75 scholarships of £1,000 available for 2016/17 and these will be paid in 2 instalments of £500 in March and June 2017.</p>");
document.write("                <a style=\"background-color: #d6d6c2;\" href=\"http:\/\/www.northampton.ac.uk\/study\/fees-and-funding\/funding-your-study\/bursaries-scholarships-and-awards\/high-achievers-scholarship\/\" target=\"_blank\">");
document.write("                View Scholarship Information<\/a>");
document.write("                    <br \/>");
document.write("                    <h4 style=\"color:#000; background-color: #bfbfbf;\">John Lowe Scholarship<\/h4>");
document.write("                        <p>The John Lowe Scholarship provides a £2,000 award to undergraduates studying within Northampton Business School, in the Field of Accounting and Finance.<br \/>");
document.write("                    <a style=\"background-color: #d6d6c2;\" href=\"http:\/\/www.northampton.ac.uk\/study\/fees-and-funding\/funding-your-study\/bursaries-scholarships-and-awards\/john-lowe-scholarship\/\" target=\"_blank\">");
document.write("                    View Scholarship");
document.write("                    <\/a>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"testimonials\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"testional_content\" style=\"text-align:center; margin-top: 16px;\">");
document.write("");
document.write("                <h3 style=\"color:#ffff00; text-decoration: underline;\">Testimonials<\/h3>");
document.write("");
document.write("                <blockquote>");
document.write("                    <span style=\"background-color: white;\">");
document.write("                       The lecturers are very helpful and supportive, willing to go the extra mile to help out thier stundents and takes an interest in helping after we finish our university course.");
document.write("                    <\/span>");
document.write("                    <br \/>");
document.write("                    <i style=\"float:right;font-weight:bold;\">");
document.write("                        2012, 3rd year, Philosophy<br \/>");
document.write("                    <\/i>");
document.write("                <\/blockquote>");
document.write("                <br \/><br \/>");
document.write("                <blockquote>");
document.write("                    <span style=\"background-color: white;\">You can meet in the outside bench area which is located outside of the student union area. You can also meet each other in the sitting area within the entrance of the library area and you can also meet each other in the restraunt with reasonable priced items.");
document.write("                    <\/span>");
document.write("                        <br \/>");
document.write("                        <i style=\"float:right; font-weight:bold;\">");
document.write("                           2012, 1st year, Public Law<br \/>");
document.write("                        <\/i>");
document.write("                <\/blockquote>");
document.write("                <br \/><br \/>");
document.write("                <blockquote>");
document.write("                    <span style=\"background-color: white;\">");
document.write("                        Lecturer support is very good");
document.write("                    <\/span>");
document.write("                    <br \/>");
document.write("                    <i style=\"float:right;font-weight:bold;\">");
document.write("                        2013, 3rd year, Accountancy<br \/>");
document.write("                    <\/i>");
document.write("                <\/blockquote><br \/><br \/><br \/>");
document.write("                ");
document.write("                <h3 style=\"color:#ffff00; text-decoration:underline; float:left;\">Student Reviews from whatuni.com<\/h3>");
document.write("                <br \/><br \/>     ");
document.write("                <b><a href=\"http:\/\/www.whatuni.com\/university-course-reviews\/university-of-northampton\/5239\/\" ");
document.write("                      class=\"review_link\" target=\"_blank\">Northampton Reviews<\/a><\/b>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"gallery\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"slideshow2\" style=\"text-align:center; margin-top: 16px;\">");
document.write("                <div>");
document.write("                    <img src=\"images\/north_campus1.jpg\" \/>");
document.write("                <\/div>");
document.write("                <div>");
document.write("                    <img src=\"images\/north_campus2.jpg\" \/>");
document.write("                <\/div>");
document.write("                <div>");
document.write("                    <img src=\"images\/north_campus3.jpg\" \/>");
document.write("                <\/div>");
document.write("                <div>");
document.write("                    <img src=\"images\/north_accom.jpg\" \/>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"social_media\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"social\">");
document.write("                <a href=\"http:\/\/www.facebook.com\/TheUniversityofNorthampton\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_facebook\" src=\"images\/facebook.png\" align=\"middle\" \/>");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Facebook<\/span>");
document.write("                <br \/><br \/><br \/>");
document.write("                <a href=\"http:\/\/twitter.com\/UniNorthants\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_twitter\" src=\"images\/twitter.png\" align=\"middle\">");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Twitter<\/span>");
document.write("                <br \/><br \/><br \/>");
document.write("                <a href=\"https:\/\/www.instagram.com\/uninorthants\/\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_insta\" src=\"images\/instagram.png\" align=\"middle\">");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Instagram<\/span>");
document.write("                <br \/><br \/><br \/>");
document.write("                <a href=\"http:\/\/www.youtube.com\/user\/UniNorthampton\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_youtube\" src=\"images\/youtube.png\" align=\"middle\">");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Youtube<\/span>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("    <\/div><!--End of northampton_dialog box div-->");