document.write(" <div id=\"notts_dialog\" style=\"display:none\" title=\"University of Nottingham Information\">");
document.write("        <div class=\"Content\">");
document.write("            <nav>");
document.write("                <ul>");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-graduation-cap\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#courses\" onclick=\"javascript:showInfo('azindex');\"><span>Courses<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-envelope-o\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#contacts\" onclick=\"javascript:showInfo('contact_index');\"><span>Contact Information<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-university\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#Scholarships\" onclick=\"javascript:showInfo('scholarships');\"><span>Scholarships<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-comment\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#testimonials\" onclick=\"javascript: showInfo('testimonials');\" ><span>Testimonials<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-picture-o\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#gallery\" onclick=\"javascript:showInfo('gallery');\"><span>Gallery<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("");
document.write("                    <li class=\"var_nav\">");
document.write("                        <div class=\"background\"><\/div>");
document.write("                        <div class=\"info_title\">");
document.write("                            <div class=icon>");
document.write("                                <i class=\"fa fa-at\" style=\"font-size:35px;\"><\/i>");
document.write("                            <\/div>");
document.write("                            <a href=\"#social_media\" onclick=\"javascript:showInfo('social_media');\"><span>Social Media Links<\/span><\/a>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("                <\/ul>");
document.write("            <\/nav>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"azindex\" class=\"menus\" style=\"display:none\">");
document.write("            <ul id=\"index\">");
document.write("                <li><a href=\"#a\" onclick=\"showCourses('a');\">A<\/a><\/li>");
document.write("                <li><a href=\"#b\" onclick=\"showCourses('b');\">B<\/a><\/li>");
document.write("                <li><a href=\"#c\" onclick=\"showCourses('c');\">C<\/a><\/li>");
document.write("                <li><a href=\"#d\" onclick=\"showCourses('d');\">D<\/a><\/li>");
document.write("                <li><a href=\"#e\" onclick=\"showCourses('e');\">E<\/a><\/li>");
document.write("                <li><a href=\"#f\" onclick=\"showCourses('f');\">F<\/a><\/li>");
document.write("                <li><a href=\"#g\" onclick=\"showCourses('g');\">G<\/a><\/li>");
document.write("                <li><a href=\"#h\" onclick=\"showCourses('h');\">H<\/a><\/li>");
document.write("                <li><a href=\"#i\" onclick=\"showCourses('i');\">I<\/a><\/li>");
document.write("                <li><a href=\"#j\" onclick=\"showCourses('j');\">J<\/a><\/li>");
document.write("                <li><a href=\"#k\" onclick=\"showCourses('k');\">K<\/a><\/li>");
document.write("                <li><a href=\"#l\" onclick=\"showCourses('l');\">L<\/a><\/li>");
document.write("                <li><a href=\"#m\" onclick=\"showCourses('m');\">M<\/a><\/li>");
document.write("                <li><a href=\"#n\" onclick=\"showCourses('n');\">N<\/a><\/li>");
document.write("                <li><a href=\"#o\" onclick=\"showCourses('o');\">O<\/a><\/li>");
document.write("                <li><a href=\"#p\" onclick=\"showCourses('p');\">P<\/a><\/li>");
document.write("                <li><a href=\"#q\" onclick=\"showCourses('q');\">Q<\/a><\/li>");
document.write("                <li><a href=\"#r\" onclick=\"showCourses('r');\">R<\/a><\/li>");
document.write("                <li><a href=\"#s\" onclick=\"showCourses('s');\">S<\/a><\/li>");
document.write("                <li><a href=\"#t\" onclick=\"showCourses('t');\">T<\/a><\/li>");
document.write("                <li><a href=\"#u\" onclick=\"showCourses('u');\">U<\/a><\/li>");
document.write("                <li><a href=\"#v\" onclick=\"showCourses('v');\">V<\/a><\/li>");
document.write("                <li><a href=\"#w\" onclick=\"showCourses('w');\">W<\/a><\/li>");
document.write("                <li><a href=\"#x\" onclick=\"showCourses('x');\">X<\/a><\/li>");
document.write("                <li><a href=\"#y\" onclick=\"showCourses('y');\">Y<\/a><\/li>");
document.write("                <li><a href=\"#z\" onclick=\"showCourses('z');\">Z<\/a><\/li>");
document.write("            <\/ul>");
document.write("");
document.write("            <div id=\"course_content\" style=\"text-align:left;\">");
document.write("                <div id=\"a\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>A<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"b\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>B<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"c\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>C<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"d\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>D<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"e\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>E<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"f\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>F<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"g\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>G<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"h\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>H<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"i\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>I<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"j\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>J<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"k\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>K<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"l\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>L<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"m\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>M<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"n\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>N<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"o\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>O<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"p\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>P<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"q\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>Q<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"r\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>R<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"s\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>S<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"t\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>T<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"u\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>U<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"v\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>V<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"w\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>W<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"x\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>X<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"y\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>Y<\/h2>");
document.write("                <\/div>");
document.write("");
document.write("                <div id=\"z\" class=\"course_a_z\" style=\"display:none; float:left; margin-top: 16px;\">");
document.write("                    <h2>Z<\/h2>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("");
document.write("        <\/div><!--End of div for the a-z index-->");
document.write("");
document.write("");
document.write("        <div id=\"contact_index\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"contact_details\" style=\"text-align:center; margin-top: 16px;\">");
document.write("                <h3 style=\"color:#ffff80; text-decoration: underline;\">University of Nottingham - Main Contact Details<\/h3>");
document.write("");
document.write("                The University of Nottingham<br \/>");
document.write("                University Park<br \/>");
document.write("                Nottingham<br \/>");
document.write("                NG7 2RD<br \/>");
document.write("                UK<br \/>");
document.write("                <strong>Tel:<\/strong> +44 (0) 115 951 5151<br \/>");
document.write("                <strong>Fax:<\/strong> +44 (0) 115 951 3666<br \/><br \/>");
document.write("");
document.write("                <strong>Undergraduate Prospectus Request<\/strong><br \/>");
document.write("                <strong>Tel:<\/strong> +44 (0) 115 951 5559 <br \/>");
document.write("                <strong>Email:<\/strong> undergraduate-enquiries@nottingham.ac.uk<br \/>");
document.write("");
document.write("                <h4 style=\"color:#990000; text-decoration: underline;\">Administrative Key Staff<\/h4>");
document.write("                <strong>Undergraduate Administrator<\/strong><br \/>");
document.write("                Ben Perrett<br \/>");
document.write("                <strong>Undergraduate Administrative Assistant<\/strong><br \/>");
document.write("                Denine Carmichael<br \/>");
document.write("");
document.write("                <h4 style=\"color:#990000; text-decoration: underline;\">Academic Key staff<\/h4>");
document.write("                <strong>Head of School<\/strong><br \/>");
document.write("                Professor Josephine Guy<br \/>");
document.write("                <strong>Director of Teaching<\/strong><br \/>");
document.write("                Dr Nicola Royan<br \/>");
document.write("                <strong>Director of Undergraduate Studies<\/strong><br \/>");
document.write("                Dr Sarah Grandage<br \/>");
document.write("                <strong>Director of Undergraduate Exams<\/strong><br \/>");
document.write("                Dr Violeta Sotirova (Autumn)<br \/>");
document.write("                Dr Abigail Ward (Spring)");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"scholarships\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"scholarship_details\" style=\"text-align:center; margin-top: 16px;\">");
document.write("               <h3 style=\"color:#fff; background-color: #e6005c; padding: 10px 0 10px 0;\">University based Scholarships<\/h3>");
document.write("                    <h4 style=\"color:#000; background-color: #bfbfbf;\">Top Class Entry Scholarship<\/h4>");
document.write("                        <p>For students in the Department of Electrical and Electronic Engineering starting in 2016.<br \/>");
document.write("                        UK and EU students only. No application required.</p>");
document.write("                <a style=\"background-color: #d6d6c2;\" href=\"https:\/\/www.nottingham.ac.uk\/engineering\/documents\/scholarships\/eee-scholarships-2016web.pdf\" target=\"_blank\">");
document.write("                View Scholarship Information<\/a>");
document.write("                    <br \/>");
document.write("                    <h4 style=\"color:#000; background-color: #bfbfbf;\">International Undergraduate Scholarships <\/h4>");
document.write("                        <p>For international students starting an undergraduate honours degree programme within the Faculty of Engineering, who meet the eligibility criteria outlined, will be awarded a fee reduction in their first year of study.<br \/>");
document.write("                        Overseas students only. No application required.</p>");
document.write("                    <a style=\"background-color: #d6d6c2;\" href=\"https:\/\/www.nottingham.ac.uk\/engineering\/documents\/scholarships\/international-scholarship-2016-web.pdf\" target=\"_blank\">");
document.write("                    View Scholarship");
document.write("                    <\/a>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"testimonials\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"testional_content\" style=\"text-align:center; margin-top: 16px;\">");
document.write("");
document.write("                <h3 style=\"color:#ffff00; text-decoration: underline;\">Testimonials<\/h3>");
document.write("");
document.write("                <blockquote>");
document.write("                    <span style=\"background-color: white;\">");
document.write("                        The University of Nottingham is very, very special. It is a pioneer.");
document.write("                        I have gone around the world saying this for the last seven years.");
document.write("                        You are the University which pushes the envelope every day.");
document.write("                        Challenging presumptions.");
document.write("                        Showing that this world has changed forever.");
document.write("                        You, at the University of Nottingham, are an exemplar in many ways.");
document.write("                    <\/span>");
document.write("                    <br \/>");
document.write("                    <i style=\"float:right;font-weight:bold;\">");
document.write("                        Lord Jones of Birmingham<br \/>");
document.write("                        Minister of State for UK Trade Promotion,<br \/>");
document.write("                        Graduation July 2007");
document.write("                    <\/i>");
document.write("                <\/blockquote>");
document.write("                <br \/><br \/>");
document.write("                <blockquote>");
document.write("                    <span style=\"background-color: white;\">Nottingham has one of the great research universities in the world.");
document.write("                    <\/span>");
document.write("                        <br \/>");
document.write("                        <i style=\"float:right; font-weight:bold;\">");
document.write("                            Richard Lambert<br \/>");
document.write("                            Director-General,<br \/>");
document.write("                            Confederation of British Industry");
document.write("                        <\/i>");
document.write("                <\/blockquote>");
document.write("                <br \/><br \/>");
document.write("                <blockquote>");
document.write("                    <span style=\"background-color: white;\">");
document.write("                        Professor Fox has particularly relevant expertise on the model dynamics of MEMS resonators.");
document.write("                        At BAE, we have a call for very specific expertise.");
document.write("                        We’re best served by picking the brains of an expert whenever we need to.");
document.write("                    <\/span>");
document.write("                    <br \/>");
document.write("                    <i style=\"float:right;font-weight:bold;\">");
document.write("                        Dr Chris Fell<br \/>");
document.write("                        Principal Consultant Engineer,<br \/>");
document.write("                        BAE Systems plc");
document.write("                    <\/i>");
document.write("                <\/blockquote><br \/><br \/><br \/>");
document.write("                ");
document.write("                <h3 style=\"color:#ffff00; text-decoration:underline; float:left;\">Student Reviews from whatuni.com<\/h3>");
document.write("                <br \/><br \/>     ");
document.write("                <b><a href=\"http:\/\/www.whatuni.com\/university-course-reviews\/university-of-nottingham\/3756\/\" ");
document.write("                      class=\"review_link\" target=\"_blank\">Nottingham Reviews<\/a><\/b>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"gallery\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"slideshow\" style=\"text-align:center; margin-top: 16px;\">");
document.write("                <div>");
document.write("                    <img src=\"images\/notts_campus1.jpg\" \/>");
document.write("                <\/div>");
document.write("                <div>");
document.write("                    <img src=\"images\/notts_campus2.jpg\" \/>");
document.write("                <\/div>");
document.write("                <div>");
document.write("                    <img src=\"images\/notts_campus3.jpg\" \/>");
document.write("                <\/div>");
document.write("                <div>");
document.write("                    <img src=\"images\/notts_accom.jpg\" \/>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("        <div id=\"social_media\" class=\"menus\" style=\"display:none\">");
document.write("            <div id=\"social\">");
document.write("                <a href=\"http:\/\/www.facebook.com\/TheUniofNottingham\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_facebook\" src=\"images\/facebook.png\" align=\"middle\" \/>");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Facebook<\/span>");
document.write("                <br \/><br \/><br \/>");
document.write("                <a href=\"http:\/\/twitter.com\/UniofNottingham\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_twitter\" src=\"images\/twitter.png\" align=\"middle\">");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Twitter<\/span>");
document.write("                <br \/><br \/><br \/>");
document.write("                <a href=\"https:\/\/www.instagram.com\/uniofnottingham\/\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_insta\" src=\"images\/instagram.png\" align=\"middle\">");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Instagram<\/span>");
document.write("                <br \/><br \/><br \/>");
document.write("                <a href=\"http:\/\/www.youtube.com\/user\/NottmUniversity\" target=\"_blank\">");
document.write("                    <img border=\"0\" alt=\"notts_youtube\" src=\"images\/youtube.png\" align=\"middle\">");
document.write("                <\/a><span style=\"text-align:center; margin-top: 24px;\">Youtube<\/span>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("");
document.write("    <\/div><!--End of notts_dialog box div-->");